# Generated by Django 5.1.7 on 2025-04-16 21:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelFam', '0002_familyrequests_created_at_familyrequests_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familyrequests',
            name='created_at',
        ),
        migrations.AddField(
            model_name='familyrequests',
            name='create_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='role',
            field=models.CharField(default='member', max_length=50),
        ),
        migrations.AlterField(
            model_name='familyrequests',
            name='status',
            field=models.CharField(choices=[('в ожидании', 'В ожидании'), ('принят', 'Принят'), ('отклонён', 'Отклонён')], default='в ожидании', max_length=10),
        ),
    ]
