# Generated by Django 5.1.7 on 2025-04-18 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelFam', '0003_remove_familyrequests_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='family',
            field=models.CharField(default='family', max_length=50),
        ),
    ]
