# Generated by Django 5.1.7 on 2025-04-18 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelFam', '0004_alter_familymember_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TravelFam.family'),
        ),
    ]
